### ISSUE TITLE
Add MANAGE_PY_PATH to the documentation

### ISSUE THREAD

**Issue by PetrDlouhy** [depop/django-concurrent-test-helper#16]
Document `MANAGE_PY_PATH` setting in some detail. I.E. for me it does not work without setting `MANAGE_PY_PATH="./manage.py"` (otherwise the error is, that `python manage.py` is not found). But I am guessed that value by try-error and I don't know what is the proper value.

**Comment by anentropic** [comment]
ah that is good to know, thanks for the report

the default is `MANAGE_PY_PATH="manage.py"` but in our own project where we use this (and also in all the test cases here) we set `MANAGE_PY_PATH="<some dir>/manage.py"` and it works fine

it needs to be set to whatever you would use to run a management command from the cli, but as you have shown you can run `$ manage.py <some command>` on the cli (unless you have added manage.py to your PATH)

so a better default value would be `MANAGE_PY_PATH="./manage.py"` since `$ ./manage.py <some command>` works fine

I will change this default
